[2023-06-09T16:15:16.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-09T16:15:16.197+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-09T16:15:16.197+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 6
[2023-06-09T16:15:16.280+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-10 00:00:00+00:00
[2023-06-09T16:15:16.327+0000] {standard_task_runner.py:57} INFO - Started process 2049 to run task
[2023-06-09T16:15:16.344+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp7leu21vi']
[2023-06-09T16:15:16.348+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask first_task
[2023-06-09T16:15:16.570+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:15:16.934+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2023-06-09T16:15:16.936+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:15:16.937+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:15:16.995+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:15:17.004+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:15:17.005+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:15:17.034+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:15:17.045+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230510T000000, start_date=20230609T161516, end_date=20230609T161517
[2023-06-09T16:15:17.082+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 67 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2049)
[2023-06-09T16:15:17.108+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:15:17.163+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
