[2023-06-09T16:12:04.640+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-09T16:12:04.681+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-09T16:12:04.684+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-09T16:12:04.737+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-10 00:00:00+00:00
[2023-06-09T16:12:04.752+0000] {standard_task_runner.py:57} INFO - Started process 1829 to run task
[2023-06-09T16:12:04.770+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpzm93kos1']
[2023-06-09T16:12:04.775+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask first_task
[2023-06-09T16:12:04.927+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-10T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:12:05.244+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2023-06-09T16:12:05.247+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:12:05.249+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:12:05.298+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:12:05.315+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:12:05.318+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:12:05.370+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:12:05.391+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230510T000000, start_date=20230609T161204, end_date=20230609T161205
[2023-06-09T16:12:05.430+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1829)
[2023-06-09T16:12:05.452+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:12:05.731+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
