[2023-06-09T16:18:13.548+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-26T00:00:00+00:00 [queued]>
[2023-06-09T16:18:13.589+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-26T00:00:00+00:00 [queued]>
[2023-06-09T16:18:13.593+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-09T16:18:13.646+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-26 00:00:00+00:00
[2023-06-09T16:18:13.662+0000] {standard_task_runner.py:57} INFO - Started process 2283 to run task
[2023-06-09T16:18:13.675+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-26T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpofv1ekct']
[2023-06-09T16:18:13.681+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask first_task
[2023-06-09T16:18:13.922+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-26T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:18:14.262+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-26T00:00:00+00:00'
[2023-06-09T16:18:14.264+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:18:14.269+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:18:14.394+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:18:14.402+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:18:14.410+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:18:14.467+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:18:14.479+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230526T000000, start_date=20230609T161813, end_date=20230609T161814
[2023-06-09T16:18:14.507+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 122 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2283)
[2023-06-09T16:18:14.564+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:18:14.733+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
