[2023-06-09T16:16:28.320+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-06-09T16:16:28.374+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-06-09T16:16:28.374+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-09T16:16:28.487+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-14 00:00:00+00:00
[2023-06-09T16:16:28.524+0000] {standard_task_runner.py:57} INFO - Started process 2133 to run task
[2023-06-09T16:16:28.571+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-14T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpupskn9f9']
[2023-06-09T16:16:28.574+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask first_task
[2023-06-09T16:16:28.951+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-14T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:16:29.388+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-14T00:00:00+00:00'
[2023-06-09T16:16:29.389+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:16:29.390+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:16:29.458+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:16:29.474+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:16:29.475+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:16:29.520+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:16:29.533+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=first_dag, task_id=first_task, execution_date=20230514T000000, start_date=20230609T161628, end_date=20230609T161629
[2023-06-09T16:16:29.592+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 87 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2133)
[2023-06-09T16:16:29.632+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:16:29.949+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
