[2023-06-09T16:19:46.740+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2023-06-09T16:19:46.751+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2023-06-09T16:19:46.751+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 6
[2023-06-09T16:19:46.769+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-19 00:00:00+00:00
[2023-06-09T16:19:46.776+0000] {standard_task_runner.py:57} INFO - Started process 2398 to run task
[2023-06-09T16:19:46.781+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-19T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmplizr_brv']
[2023-06-09T16:19:46.784+0000] {standard_task_runner.py:85} INFO - Job 150: Subtask first_task
[2023-06-09T16:19:46.847+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-19T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:19:46.965+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-19T00:00:00+00:00'
[2023-06-09T16:19:46.977+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:19:46.978+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:19:46.997+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:19:46.999+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:19:46.999+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:19:47.023+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:19:47.034+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230519T000000, start_date=20230609T161946, end_date=20230609T161947
[2023-06-09T16:19:47.064+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 150 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2398)
[2023-06-09T16:19:47.079+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:19:47.104+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
