[2023-06-09T16:15:40.696+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-09T16:15:40.720+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-06-09T16:15:40.721+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 6
[2023-06-09T16:15:40.766+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-04 00:00:00+00:00
[2023-06-09T16:15:40.779+0000] {standard_task_runner.py:57} INFO - Started process 2070 to run task
[2023-06-09T16:15:40.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwuebrlb5']
[2023-06-09T16:15:40.796+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask first_task
[2023-06-09T16:15:41.092+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-04T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:15:41.696+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-06-09T16:15:41.699+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:15:41.700+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:15:41.727+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:15:41.756+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:15:41.760+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:15:41.847+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:15:41.915+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230504T000000, start_date=20230609T161540, end_date=20230609T161541
[2023-06-09T16:15:42.065+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2070)
[2023-06-09T16:15:42.096+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:15:42.200+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
