[2023-06-09T16:14:56.358+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-18T00:00:00+00:00 [queued]>
[2023-06-09T16:14:56.437+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-18T00:00:00+00:00 [queued]>
[2023-06-09T16:14:56.437+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 6
[2023-06-09T16:14:56.532+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-18 00:00:00+00:00
[2023-06-09T16:14:56.560+0000] {standard_task_runner.py:57} INFO - Started process 2031 to run task
[2023-06-09T16:14:56.594+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-18T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0qnmcrue']
[2023-06-09T16:14:56.620+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask first_task
[2023-06-09T16:14:56.969+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-18T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:14:58.015+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-18T00:00:00+00:00'
[2023-06-09T16:14:58.016+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:14:58.017+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:14:58.094+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:14:58.102+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:14:58.103+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:14:58.174+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:14:58.232+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230518T000000, start_date=20230609T161456, end_date=20230609T161458
[2023-06-09T16:14:58.306+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 66 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2031)
[2023-06-09T16:14:58.393+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:14:58.516+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
