[2023-06-10T06:46:34.598+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-06-10T06:46:34.795+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-06-10T06:46:34.805+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-10T06:46:36.505+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): greet> on 2023-05-12 00:00:00+00:00
[2023-06-10T06:46:36.628+0000] {standard_task_runner.py:57} INFO - Started process 12197 to run task
[2023-06-10T06:46:36.660+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xcom_operator_with_function', 'greet', 'scheduled__2023-05-12T00:00:00+00:00', '--job-id', '777', '--raw', '--subdir', 'DAGS_FOLDER/xcom_operator.py', '--cfg-path', '/tmp/tmpq7udyke1']
[2023-06-10T06:46:36.671+0000] {standard_task_runner.py:85} INFO - Job 777: Subtask greet
[2023-06-10T06:46:37.851+0000] {task_command.py:410} INFO - Running <TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-12T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-10T06:46:38.773+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='xcom_operator_with_function' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-12T00:00:00+00:00'
[2023-06-10T06:46:38.774+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'it'
[2023-06-10T06:46:38.821+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=xcom_operator_with_function, task_id=greet, execution_date=20230512T000000, start_date=20230610T064634, end_date=20230610T064638
[2023-06-10T06:46:38.876+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 777 for task greet (greet() missing 1 required positional argument: 'it'; 12197)
[2023-06-10T06:46:38.922+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-10T06:46:39.122+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
