[2023-06-10T11:01:22.343+0000] {task_command.py:410} INFO - Running <TaskInstance: xcom_operator_with_function_v2.greet manual__2023-06-10T10:54:37.956370+00:00 [None]> on host 93a4f35889be
[2023-06-10T11:01:24.008+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='xcom_operator_with_function_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-06-10T10:54:37.956370+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-10T10:54:37.956370+00:00'
[2023-06-10T11:01:24.009+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2023-06-10T11:01:24.119+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=xcom_operator_with_function_v2, task_id=greet, execution_date=20230610T105437, start_date=20230610T105612, end_date=20230610T110124
[2023-06-10T11:01:26.260+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 976 for task greet (greet() missing 1 required positional argument: 'age'; 15831)
[2023-06-10T11:06:31.615+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_operator_with_function_v2.greet manual__2023-06-10T10:54:37.956370+00:00 [queued]>
[2023-06-10T11:06:31.833+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_operator_with_function_v2.greet manual__2023-06-10T10:54:37.956370+00:00 [queued]>
[2023-06-10T11:06:31.834+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-10T11:06:32.181+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): greet> on 2023-06-10 10:54:37.956370+00:00
[2023-06-10T11:06:32.233+0000] {standard_task_runner.py:57} INFO - Started process 16104 to run task
[2023-06-10T11:06:32.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xcom_operator_with_function_v2', 'greet', 'manual__2023-06-10T10:54:37.956370+00:00', '--job-id', '1006', '--raw', '--subdir', 'DAGS_FOLDER/xcom_operator.py', '--cfg-path', '/tmp/tmpskmijf80']
[2023-06-10T11:06:32.305+0000] {standard_task_runner.py:85} INFO - Job 1006: Subtask greet
[2023-06-10T11:06:32.643+0000] {task_command.py:410} INFO - Running <TaskInstance: xcom_operator_with_function_v2.greet manual__2023-06-10T10:54:37.956370+00:00 [running]> on host 93a4f35889be
[2023-06-10T11:06:33.334+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='xcom_operator_with_function_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-06-10T10:54:37.956370+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-10T10:54:37.956370+00:00'
[2023-06-10T11:06:33.336+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2023-06-10T11:06:33.419+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=xcom_operator_with_function_v2, task_id=greet, execution_date=20230610T105437, start_date=20230610T110631, end_date=20230610T110633
[2023-06-10T11:06:33.526+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1006 for task greet (greet() missing 1 required positional argument: 'age'; 16104)
[2023-06-10T11:06:33.617+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-10T11:06:33.790+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
