[2023-06-09T16:19:12.348+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-06-09T16:19:12.361+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-06-09T16:19:12.362+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2023-06-09T16:19:12.393+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-22 00:00:00+00:00
[2023-06-09T16:19:12.402+0000] {standard_task_runner.py:57} INFO - Started process 2345 to run task
[2023-06-09T16:19:12.421+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-22T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpa1l4qz4t']
[2023-06-09T16:19:12.424+0000] {standard_task_runner.py:85} INFO - Job 137: Subtask first_task
[2023-06-09T16:19:12.544+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-22T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:19:12.746+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-22T00:00:00+00:00'
[2023-06-09T16:19:12.748+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:19:12.749+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:19:12.766+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:19:12.769+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:19:12.778+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:19:12.799+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:19:12.804+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230522T000000, start_date=20230609T161912, end_date=20230609T161912
[2023-06-09T16:19:12.826+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 137 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2345)
[2023-06-09T16:19:12.873+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:19:12.932+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
