[2023-06-09T16:21:27.784+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-27T00:00:00+00:00 [queued]>
[2023-06-09T16:21:27.838+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-27T00:00:00+00:00 [queued]>
[2023-06-09T16:21:27.839+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 6
[2023-06-09T16:21:27.886+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-27 00:00:00+00:00
[2023-06-09T16:21:27.904+0000] {standard_task_runner.py:57} INFO - Started process 2511 to run task
[2023-06-09T16:21:27.918+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-27T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpi0g9z9i1']
[2023-06-09T16:21:27.930+0000] {standard_task_runner.py:85} INFO - Job 173: Subtask first_task
[2023-06-09T16:21:28.136+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-27T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:21:28.538+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-27T00:00:00+00:00'
[2023-06-09T16:21:28.541+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:21:28.542+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:21:28.577+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:21:28.584+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:21:28.586+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:21:28.619+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:21:28.638+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230527T000000, start_date=20230609T162127, end_date=20230609T162128
[2023-06-09T16:21:28.706+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 173 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2511)
[2023-06-09T16:21:28.736+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:21:28.803+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
