[2023-06-09T16:17:06.132+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2023-06-09T16:17:06.195+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2023-06-09T16:17:06.195+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-09T16:17:06.394+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-05-20 00:00:00+00:00
[2023-06-09T16:17:06.419+0000] {standard_task_runner.py:57} INFO - Started process 2194 to run task
[2023-06-09T16:17:06.437+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-05-20T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpi2fhayiz']
[2023-06-09T16:17:06.565+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask first_task
[2023-06-09T16:17:07.010+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-05-20T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:17:07.715+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-20T00:00:00+00:00'
[2023-06-09T16:17:07.719+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:17:07.720+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:17:07.798+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:17:07.822+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:17:07.822+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:17:07.874+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:17:07.915+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230520T000000, start_date=20230609T161706, end_date=20230609T161707
[2023-06-09T16:17:08.016+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 104 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2194)
[2023-06-09T16:17:08.092+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:17:08.217+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
