[2023-06-10T06:41:25.453+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-10T06:41:25.802+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-06-10T06:41:25.802+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-10T06:41:26.044+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): greet> on 2023-05-10 00:00:00+00:00
[2023-06-10T06:41:26.092+0000] {standard_task_runner.py:57} INFO - Started process 11885 to run task
[2023-06-10T06:41:26.107+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xcom_operator_with_function', 'greet', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/xcom_operator.py', '--cfg-path', '/tmp/tmpy8trartw']
[2023-06-10T06:41:26.184+0000] {standard_task_runner.py:85} INFO - Job 756: Subtask greet
[2023-06-10T06:41:26.805+0000] {task_command.py:410} INFO - Running <TaskInstance: xcom_operator_with_function.greet scheduled__2023-05-10T00:00:00+00:00 [running]> on host 93a4f35889be
[2023-06-10T06:41:28.050+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='xcom_operator_with_function' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2023-06-10T06:41:28.052+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'it'
[2023-06-10T06:41:28.126+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=xcom_operator_with_function, task_id=greet, execution_date=20230510T000000, start_date=20230610T064125, end_date=20230610T064128
[2023-06-10T06:41:28.196+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 756 for task greet (greet() missing 1 required positional argument: 'it'; 11885)
[2023-06-10T06:41:28.236+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-10T06:41:28.305+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
