[2023-06-09T16:20:44.549+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [queued]>
[2023-06-09T16:20:44.561+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [queued]>
[2023-06-09T16:20:44.562+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 6
[2023-06-09T16:20:44.583+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-06-09 16:16:33.747489+00:00
[2023-06-09T16:20:44.590+0000] {standard_task_runner.py:57} INFO - Started process 2467 to run task
[2023-06-09T16:20:44.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'manual__2023-06-09T16:16:33.747489+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpf1jemh_4']
[2023-06-09T16:20:44.600+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask first_task
[2023-06-09T16:20:44.685+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:20:44.823+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T16:16:33.747489+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T16:16:33.747489+00:00'
[2023-06-09T16:20:44.825+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:20:44.827+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:20:44.845+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:20:44.848+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:20:44.848+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:20:44.866+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:20:44.872+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, execution_date=20230609T161633, start_date=20230609T162044, end_date=20230609T162044
[2023-06-09T16:20:44.888+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 165 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2467)
[2023-06-09T16:20:44.937+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:20:44.969+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
