[2023-06-09T16:21:46.806+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [queued]>
[2023-06-09T16:21:46.835+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [queued]>
[2023-06-09T16:21:46.835+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-09T16:21:46.866+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-06-09 16:16:33.747489+00:00
[2023-06-09T16:21:46.874+0000] {standard_task_runner.py:57} INFO - Started process 2544 to run task
[2023-06-09T16:21:46.882+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'manual__2023-06-09T16:16:33.747489+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1294c67q']
[2023-06-09T16:21:46.886+0000] {standard_task_runner.py:85} INFO - Job 183: Subtask first_task
[2023-06-09T16:21:47.026+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.first_task manual__2023-06-09T16:16:33.747489+00:00 [running]> on host 93a4f35889be
[2023-06-09T16:21:47.195+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='madhu' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T16:16:33.747489+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T16:16:33.747489+00:00'
[2023-06-09T16:21:47.198+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-09T16:21:47.199+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello world i am madhu']
[2023-06-09T16:21:47.216+0000] {subprocess.py:86} INFO - Output:
[2023-06-09T16:21:47.219+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-06-09T16:21:47.219+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-09T16:21:47.243+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-09T16:21:47.251+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=first_dag, task_id=first_task, execution_date=20230609T161633, start_date=20230609T162146, end_date=20230609T162147
[2023-06-09T16:21:47.278+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 183 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 2544)
[2023-06-09T16:21:47.316+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T16:21:47.357+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
